pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'python -m py_compile /var/lib/jenkins/workspace/simple-pyth>
                stash(name: 'compiled-results', includes: 'sources/calc.py')
            }
        }
    }
}

